import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Navbar } from '@/widgets/navbar'
import { Sidebar } from '@/widgets/sidebar'
import './globals.css'
import { Card } from '@/components/ui/card'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex gap-4 w-screen h-screen p-4">
            <aside className="w-1/4 h-full">
              <Card className="p-6 w-full h-full">
                <Sidebar />
              </Card>
            </aside>
            <div className="w-3/4">
              <Card className=" w-full h-full">
                <Navbar />
                <main className="grow">
                  <div className="p-6">{props.children}</div>
                  {/*<ScrollArea className="p-6">{props.children}</ScrollArea>*/}
                </main>
              </Card>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
